DATA PANELSCANNER;
INFILE "H:\hhclean_PANEL_GR_1114_1165.dat" FIRSTOBS =2 dlm="09"x;
INPUT PANID WEEK UNITS OUTLET $ DOLLARS IRI_KEY COLUPC;
RUN;

PROC IMPORT DATAFILE= 'H:\ads demo3.csv' OUT=DEMOGRAPHICS DBMS=CSV;
RUN;

DATA STOREINFO;
INFILE "H:\Delivery_Stores" FIRSTOBS =2;
INPUT IRI_KEY 1-8 OU $ 9-10  EST_ACV 12-19 Market_Name $ 21-44  Open 46-49 Clsd 51-54 MskdName $  56-63  ;
RUN;

DATA SCANNERGROC;
INFILE "H:\hhclean_groc_1114_1165" FIRSTOBS =2;
INPUT IRI_KEY 1-7 WEEK 9-12 SY 14-15 GE 17-18 VEND 20-24  ITEM 26-30  UNITS 32-36 DOLLARS 38-45 F $ 46-50 D 52 PR 54 ;
RUN;

PROC IMPORT DATAFILE= 'H:\IRI_week.xls' OUT=IRIWEEK DBMS=XLS;
RUN;

PROC IMPORT DATAFILE= 'H:\prod_hhclean.xls' OUT=work.Product DBMS=XLS;
RUN;

DATA SCANNERGROC1;
	SET SCANNERGROC(rename = (SY = SYnum GE = GEnum VEND = VENDnum ITEM = ITEMnum));
	FORMAT colupc 20.;
	colupc = SYnum*100000000000+GEnum*10000000000+VENDnum*100000+ITEMnum;
	SY = put(SYnum, 5.);
	GE = put(GEnum, 5.);
	VEND = put(VENDnum, 10.);
	ITEM = put(ITEMnum, 10.);
	DROP SYnum GEnum VENDnum ITEMnum;
RUN;

PROC SORT DATA = SCANNERGROC1;
	BY colupc;
RUN;

DATA Product1;
SET Product(rename = (SY = SYnum GE = GEnum VEND = VENDnum ITEM = ITEMnum));
FORMAT colupc 20.;
    colupc = SYnum*100000000000+GEnum*10000000000+VENDnum*100000+ITEMnum;
	SY = put(SYnum, 5.);
	GE = put(GEnum, 5.);
	VEND = put(VENDnum, 10.);
	ITEM = put(ITEMnum, 10.);
	DROP SYnum GEnum VENDnum ITEMnum;
RUN;

PROC SORT DATA = Product1;
	BY colupc;
RUN;

DATA MASTER;
MERGE SCANNERGROC1 Product1;
BY colupc;
RUN;

DATA MASTER;
SET MASTER;
IF cmiss(of _all_) then DELETE;
RUN;

DATA ALLPURPOSE;
SET MASTER;
WHERE TYPE_OF_CLEANER_DISF = "ALL PURPOSE";
RUN;

DATA ALLPURPOSE;
SET ALLPURPOSE;
DROP L1 L2 L4 LEVEL PRODUCT_TYPE FLAVOR_SCENT STRENGTH ADDITIVES CONCENTRATION_LEVEL;
RUN;


PROC SORT DATA = ALLPURPOSE;
BY L5;
RUN;

DATA TOPBRANDS;
SET ALLPURPOSE;
RUN;

PROC SUMMARY DATA = TOPBRANDS;
	CLASS L5;
	VAR DOLLARS;
	OUTPUT OUT = TOP SUM = DOLLARS;
RUN;

PROC SORT DATA = TOP(keep = L5 DOLLARS);
	BY descending DOLLARS;
RUN;

*Regression for Clorox Clean Up Brand;
DATA ALLPURPOSE_CLOROX;
SET ALLPURPOSE;
WHERE L5 ="CLOROX CLEAN UP";
RUN;

DATA ALLPURPOSE_CLOROX;
SET ALLPURPOSE_CLOROX;
UNITS_OZ = UNITS*16*VOL_EQ;
DOLLARS_OZ = DOLLARS/(16*VOL_EQ*UNITS);
RUN;

PROC SUMMARY DATA = ALLPURPOSE_CLOROX NWAY;
CLASS WEEK colupc;
VAR UNITS_OZ;
OUTPUT OUT = UNITS_CLOROX SUM = UNITS_OZ;
RUN;

PROC SUMMARY DATA = ALLPURPOSE_CLOROX NWAY;
CLASS WEEK;
VAR UNITS_OZ;
OUTPUT OUT = UNITS1_CLOROX(RENAME=(UNITS_OZ = SUM_OF_UNITS_OZ)) SUM = UNITS_OZ;
RUN;

PROC SORT DATA = UNITS_CLOROX;
BY WEEK;
RUN;

PROC SORT DATA = UNITS1_CLOROX;
BY WEEK;
RUN;

TITLE1 "Sales By Volume(OZ)";
PROC SGPLOT DATA=UNITS1_CLOROX;
   SERIES X=WEEK Y=SUM_OF_UNITS_OZ / markers;
   /* xaxis values=('1jan80'd to '1jan92'd by year);
   yaxis values=(6000 to 24000 by 3000);
   format date year4.;*/
RUN;

PROC FORECAST DATA=UN_CL INTERVAL=WEEK
              METHOD=WINTERS SEASONS=2 LEAD=12
              OUT=OUT OUTFULL OUTRESID OUTEST=EST;
   ID WEEK;
   VAR UN_OZ;
   /*where date >= '1jan80'd;*/
RUN;

DATA UN_CL;
MERGE IRIWEEK UNITS1_CLOROX;
BY WEEK;
RUN;

PROC TIMESERIES DATA = UN_CL PLOT=SERIES;
   ID END INTERVAL = WEEK;
   VAR SUM_OF_UNITS_OZ;
RUN;

DATA UN_CL;
SET UN_CL;
UN_OZ = LOG(SUM_OF_UNITS_OZ);
RUN;

PROC ARIMA DATA = UN_CL;
   IDENTIFY VAR = UN_OZ;
   ESTIMATE Q =(1)(24) NOINT METHOD=EXPO;
   FORECAST ID = END INTERVAL = WEEK PRINTALL OUT = B;
RUN;


DATA WEIGHTS_CLOROX;
MERGE UNITS_CLOROX UNITS1_CLOROX;
BY WEEK;
RUN;

DATA WEIGHTS_CLOROX;
SET WEIGHTS_CLOROX;
UNIT_WT_OZ = UNITS_OZ/SUM_OF_UNITS_OZ;
RUN;

PROC SORT DATA = WEIGHTS_CLOROX;
BY colupc;
RUN;

PROC SORT DATA = ALLPURPOSE_CLOROX;
BY colupc;
RUN;

DATA CLOROX_SCANNER;
MERGE WEIGHTS_CLOROX ALLPURPOSE_CLOROX;
BY colupc;
RUN;

DATA CLOROX_SCANNER1;
SET CLOROX_SCANNER;
if F='A+' then F_APLUS=1;else F_APLUS=0;
if F='A' then F_A=1;else F_A=0;
if F='B' then F_B=1;else F_B=0;
if F='C' then F_C=1;else F_C=0;
DOLLARS_WT = UNIT_WT_OZ*DOLLARS_OZ;
D_WT = UNIT_WT_OZ*D;
F_APLUS_WT = UNIT_WT_OZ*F_APLUS;
F_A_WT = UNIT_WT_OZ*F_A;
F_B_WT = UNIT_WT_OZ*F_B;
F_C_WT = UNIT_WT_OZ*F_C;
RUN;

DATA CLOROX_SCANNER1;
SET CLOROX_SCANNER1;
UNITS_OZ_LOG = LOG(UNITS_OZ);
DOLLARS_WT_LOG = LOG(DOLLARS_WT);
RUN;

DATA CLOROX_SCANNER_FINAL;
SET CLOROX_SCANNER1;
KEEP L3 L5 COLUPC UNITS_OZ UNITS_OZ_LOG DOLLARS_WT DOLLARS_WT_LOG D_WT F_APLUS_WT F_A_WT F_B_WT F_C_WT PR;
RUN;

PROC REG DATA = CLOROX_SCANNER_FINAL;
MODEL UNITS_OZ_LOG = DOLLARS_WT D_WT F_APLUS_WT F_A_WT F_B_WT F_C_WT PR/ stb;
RUN;

PROC REG DATA = CLOROX_SCANNER_FINAL;
MODEL UNITS_OZ_LOG = DOLLARS_WT_LOG;
RUN;

*Regression for Pine Sol Brand;
DATA ALLPURPOSE_PINESOL;
SET ALLPURPOSE;
WHERE L5 ="PINE SOL";
RUN;

DATA ALLPURPOSE_PINESOL;
SET ALLPURPOSE_PINESOL;
UNITS_OZ = UNITS*16*VOL_EQ;
DOLLARS_OZ = DOLLARS/(16*VOL_EQ*UNITS);
RUN;

PROC SUMMARY DATA = ALLPURPOSE_PINESOL NWAY;
CLASS WEEK colupc;
VAR UNITS_OZ;
OUTPUT OUT = UNITS_PINESOL SUM = UNITS_OZ;
RUN;

PROC SUMMARY DATA = ALLPURPOSE_PINESOL NWAY;
CLASS WEEK;
VAR UNITS_OZ;
OUTPUT OUT = UNITS1_PINESOL(RENAME=(UNITS_OZ = SUM_OF_UNITS_OZ)) SUM = UNITS_OZ;
RUN;

PROC SORT DATA = UNITS_PINESOL;
BY WEEK;
RUN;

PROC SORT DATA = UNITS1_PINESOL;
BY WEEK;
RUN;

DATA WEIGHTS_PINESOL;
MERGE UNITS_PINESOL UNITS1_PINESOL;
BY WEEK;
RUN;

DATA WEIGHTS_PINESOL;
SET WEIGHTS_PINESOL;
UNIT_WT_OZ = UNITS_OZ/SUM_OF_UNITS_OZ;
RUN;

PROC SORT DATA = WEIGHTS_PINESOL;
BY colupc;
RUN;

PROC SORT DATA = ALLPURPOSE_PINESOL;
BY colupc;
RUN;

DATA PINESOL_SCANNER;
MERGE WEIGHTS_PINESOL ALLPURPOSE_PINESOL;
BY colupc;
RUN;

DATA PINESOL_SCANNER1;
SET PINESOL_SCANNER;
if F='A+' then F_APLUS=1;else F_APLUS=0;
if F='A' then F_A=1;else F_A=0;
if F='B' then F_B=1;else F_B=0;
if F='C' then F_C=1;else F_C=0;
DOLLARS_WT = UNIT_WT_OZ*DOLLARS_OZ;
D_WT = UNIT_WT_OZ*D;
F_APLUS_WT = UNIT_WT_OZ*F_APLUS;
F_A_WT = UNIT_WT_OZ*F_A;
F_B_WT = UNIT_WT_OZ*F_B;
F_C_WT = UNIT_WT_OZ*F_C;
RUN;

DATA PINESOL_SCANNER1;
SET PINESOL_SCANNER1;
UNITS_OZ_LOG = LOG(UNITS_OZ);
DOLLARS_WT_LOG = LOG(DOLLARS_WT);
RUN;

DATA PINESOL_SCANNER_FINAL;
SET PINESOL_SCANNER1;
KEEP L3 L5 COLUPC UNITS_OZ UNITS_OZ_LOG DOLLARS_WT DOLLARS_WT_LOG D_WT F_APLUS_WT F_A_WT F_B_WT F_C_WT PR;
RUN;

PROC REG DATA = PINESOL_SCANNER_FINAL;
MODEL UNITS_OZ_LOG = DOLLARS_WT_LOG D_WT F_APLUS_WT F_A_WT F_B_WT F_C_WT PR/ stb;
RUN;

*Demographics info for CLOROX;
PROC SORT DATA = PANELSCANNER;
BY COLUPC;
RUN;

PROC SORT DATA = CLOROX_SCANNER_FINAL;
BY COLUPC;
RUN;

DATA MASTERPANEL_CLOROX;
MERGE PANELSCANNER CLOROX_SCANNER_FINAL;
BY COLUPC;
RUN;

DATA MASTERPANEL_CLOROX;
SET MASTERPANEL_CLOROX;
IF cmiss(of _all_) then DELETE;
RUN;

PROC SUMMARY DATA = MASTERPANEL_CLOROX NWAY;
CLASS PANID WEEK;
VAR UNITS_OZ;
OUTPUT OUT = UNITS_PANID SUM = UNITS_OZ;
RUN;

PROC SORT DATA = DEMOGRAPHICS;
BY PANID;
RUN;

DATA PANELDEMO_CLOROX;
MERGE UNITS_PANID DEMOGRAPHICS;
BY PANID;
RUN;

DATA PANELDEMO_CLOROX;
SET PANELDEMO_CLOROX;
DROP _TYPE_ _FREQ_;
IF missing(WEEK) then DELETE;
IF missing(Combined_Pre_Tax_Income_of_HH) then DELETE;
IF missing(Family_Size) then DELETE;
IF missing(Children_Group_Code) then DELETE;
RUN;


PROC PANEL DATA = PANELDEMO_CLOROX;
ID PANID WEEK;
MODEL UNITS_OZ = Combined_Pre_Tax_Income_of_HH Family_Size Children_Group_Code / RANONE;
RUN;




